version: "2.2"

services:
    certhunt:
        container_name: certhunt
        build: certhunt
        restart: unless-stopped
        volumes:
          - ./data/certhunt/certhunt.log:/app/certhunt.log
          - ./data/certhunt/attributes.jsonl:/app/attributes.jsonl
        depends_on:
          - redis
    mispbridge:
        build: misp-bridge
        restart: unless-stopped
        environment:
          - MISP_URL
          - MISP_KEY
          - MISP_VERIFYCERT
        depends_on:
          - redis
    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
          - ./data/redis:/data

    # Restart certhunt daily due to suspected memory leak
    restarter:
        container_name: certhunt_restarter
        image: docker
        volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
        command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart certhunt; done"]
        restart: unless-stopped
    # https://gist.github.com/kizzx2/782b500a81ce46b889903b1f80353f21
