version: "2.2"

services:
    tasker:
        build: tasker
        restart: unless-stopped
        environment:
          - TWITTER_KEY
          - TWITTER_SECRET
          - URLSCAN_KEY
        depends_on:
          - redis
    certhunt:
        container_name: certhunt
        build: certhunt
        restart: unless-stopped
        environment:
          - GOMEMLIMIT=10MiB
        volumes:
          - ./data/certhunt/certhunt.log:/app/certhunt.log
          - ./data/certhunt/attributes.jsonl:/app/attributes.jsonl
    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
          - ./data/redis:/data

    # Restart certhunt daily due to suspected memory leak
    restarter:
        image: docker
        volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
        command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart certhunt; done"]
        restart: unless-stopped
    # https://gist.github.com/kizzx2/782b500a81ce46b889903b1f80353f21
