version: "2.2"

services:
    tasker:
        build: tasker
        restart: unless-stopped
        environment:
          - TWITTER_KEY
          - TWITTER_SECRET
          - URLSCAN_KEY
        depends_on:
          - redis
    certstream:
        build: certstream
        restart: unless-stopped
        environment:
          - GOMEMLIMIT=10MiB
    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
          - ./data/redis:/data
